packages:
  - apps/*
  - packages/*

nodeLinker: hoisted
autoInstallPeers: true
strictPeerDependencies: false
shamefullyHoist: true

supportedArchitectures:
  os:
    - current
    - darwin
    - win32
  cpu:
    - current
    - arm64
    - x64
  libc:
    - current

allowBuilds:
  better-sqlite3: set this to true or false
